version: '3.2'
services:
  picobox:
    container_name: picobox
    build:
      context: .
      dockerfile: Dockerfile
    image: picobox
    environment:
      - PUID=1000
      - PGID=1000
      - PICO_SDK_PATH:/pico-sdk/
    volumes:
      - $HOME/src/dev/wear-pico/wear-pico/:/app/
      - $HOME/src/dev/wear-pico/wear-pico/pico-sdk/:/pico-sdk/
    command: bash -c "echo OK;env; sleep infinity"
    privileged: true

